### DISCUSSION TITLE
怎样为自己写的插件，在应用中增加配置选项？

### DISCUSSION THREAD

**Discussion by iQuick** [Flow-Launcher/Flow.Launcher#1207] [Q&A] [answered]
如题，我自己写了个插件。
我想为插件增加一些选项配置，请问这个需要怎么操作呢。
类似这样的
![image](https://user-images.githubusercontent.com/7509014/168195207-3af1e32f-093e-45c4-8eb3-4437dd0f846f.png)

**Comment by taooceros** [comment, marked as answer]
c#还是python

**Reply by iQuick** [reply]
python 的，我正在写一个 python 的翻译插件。

**Reply by iQuick** [reply]
@taooceros

**Reply by taooceros** [reply]
参考下这里#657

**Reply by iQuick** [reply]
@taooceros 我已经在我的插件目录中添加 SettingsTemplate.yaml 配置文件，但是我的插件下面并没有配置选项

**Reply by taooceros** [reply]
> @taooceros 我已经在我的插件目录中添加 SettingsTemplate.yaml 配置文件，但是我的插件下面并没有配置选项

可以给我看看这个yaml是怎么写的嘛

**Comment by iQuick** [comment]
我是参考示例 copy 了一份

```
- type: textarea/input
  attributes:
    label: Label to be displayed before the control
    description: Not yet implemented (probably tooltip)
    placeholder: Not yet implemented 
    name: identifier of the control
    defaultValue: Default Value of the control
- type: password
   attributes:
    label: Label to be displayed before the control
    description: Not yet implemented (probably tooltip)
    placeholder: Not yet implemented 
    name: identifier of the control
    defaultValue: Default Value of the control
    passwordChar: char to mask the actual input 
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - label: 1.0.2 (Default)
      - label: 1.0.3 (Edge)
  validations:
    required: true
- type: checkbox
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    defaultValue: true
```

![image](https://user-images.githubusercontent.com/7509014/169185840-6d97a911-c5f4-4c22-a88a-a532c39337b3.png)
