### ISSUE TITLE
BUG: Can't get plugin settings from SettingsTemplate.yaml to appear in Flow Settings page

### ISSUE THREAD

**Issue by bmyonatan** [Flow-Launcher/Flow.Launcher#2531]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When developing a plugin, I try to include user defined settings by placing a `SettingsTemplate.yaml` file in the plugin root directory, however the settings don't appear in the settings gui.
Changing an existing plugins (for example HA-Commander) `SettingsTemplate.yaml` (and then restarting flow) does show the change in that plugins settings.
Copying the same `SettingsTemplate.yaml` to my plugin doesn't work either.

### To Reproduce

My Folder structure is:
- Plugin Name
    - plugin.json
    - main.py
    - icon.png
    - SettingsTemplate.yaml

### Flow Launcher Version

1.17.0

### Windows Build Number

10.0.22621.3085

### Error Log

No related log messages

**Comment by Garulf** [comment]
Hello @bmyonatan, 

Going by what you’re stating I don't see any reason it would not show. 

@bmyonatan Are you able to please share the source for your plugin?

**Comment by bmyonatan** [comment]
sure
plugin.json:
```
{
    "ID": "86992ca7-77f6-496c-a353-3edfd76f51b1",
    "ActionKeyword": "conf",
    "Name": "SearchConfluence",
    "Description": "Search Confluence",
    "Author": "bmyontatan",
    "Version": "0.0.1",
    "Language": "python",
    "Website": "http://localhost:8091",
    "IcoPath": "confluence.png",
    "ExecuteFileName": "main.py"
  }
```

SettingsTemplate.yaml:
```
body:
  - type: input
    attributes:
        name: conf_url
        label: 'Confluence URL:'
        defaultValue: "http://localhost:8091"
        description: Confluence URL
  - type: input
    attributes:
      name: conf_username
      label: 'Confluence Username'
      defaultValue: ""
      description: Confluence Username
  - type: passwordBox
    attributes:
      name: conf_password
      label: 'Confluence Password'
      defaultValue: ""
      description: Confluence Password
```

main.py:
```
from pyflowlauncher import Plugin, Result, send_results, api
from atlassian import Confluence

plugin = Plugin()

CONF_URL = plugin.settings['conf_url']
CQL_TEMPLATE = 'title ~ "{}" and type IN (blogpost, page)'

confluence = Confluence(url=CONF_URL,
                        username=plugin.settings['conf_username'],
                        password=plugin.settings['conf_password'])


@plugin.on_method
def query(query):
    flow_results = []
    conf_results = confluence.cql(CQL_TEMPLATE.format(query))['results']
    if len(conf_results) == 0:
        r = Result(
            Title=f'No Results Found for "{query}"',
            IcoPath="confluence.png",
        )
        flow_results.append(r)
        return send_results(flow_results)
    for search_res in conf_results:
        title = search_res['content']['title']
        space = search_res['content']['_expandable']['space'].split('/')[-1]
        excerpt = search_res['excerpt']
        url = CONF_URL + search_res['url']
        r = Result(
            Title=f"{space}: {title}",
            SubTitle=excerpt,
            IcoPath="confluence.png",
            JsonRPCAction=api.open_url(url)
        )
        flow_results.append(r)
    return send_results(flow_results)

plugin.run()
```

**Comment by bmyonatan** [comment]
Using the same code on Flow version 1.16.2 shows all settings properly
Semms like something broke in the update to 1.17.0

**Comment by Yusyuriv** [comment]
I don't know why this is happening, but I can confirm that it does happen. For example, here's `SettingsTemplate.yaml` from the ChatGPT plugin:
<details>

```yml
body:
  - type: passwordBox
    attributes:
      name: api_key
      label: "API Key:"
      defaultValue: ""
      description: OpenAI API Key
  - type: dropdown
    attributes:
      name: model
      label: "Model:"
      defaultValue: gpt-3.5-turbo
      options:
        - gpt-3.5-turbo
        - gpt-4
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-1106-preview
        - gpt-4-0613
  - type: input
    attributes:
      name: prompt_stop
      label: "Prompt stop:"
      defaultValue: "||"
      description: Characters to indicate end of prompt
  - type: input
    attributes:
      name: default_prompt
      label: "Default system prompt:"
      defaultValue: "normal"
      description: Default key word that will be looked up in the system_messages.csv file
  - type: checkbox
    attributes:
      name: save_conversation
      label: 'Save conversation:'
      defaultValue: no
      description: Check to save the conversations for each prompt type in a .txt file in the plugin folder
  - type: dropdown
    attributes:
      name: log_level
      label: "Log Level:"
      defaultValue: error
      options:
        - info
        - debug
        - warning
        - error
        - critical
```

</details>

None of the settings show up at all until I invoke the plugin at least once after Flow Launcher's restart:
![Screenshot 1 of the ChatGPT plugin](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/9ae19f68-1199-40c1-9e6e-6597db475209)
After invoking the plugin once, they appear:
![Screenshot 2 of the ChatGPT plugin](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/a67928c6-edc8-4e18-9902-859d4c7f3204)

Another example, FlowYouTube. Settings just don't show up at all, even after invoking the plugin:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/3b20f9a5-0c04-4323-9bcf-404fe74f40a5)
Here's its `SettingsTemplate.yaml`:
<details>

```yml
body:
  - type: dropdown
    attributes:
      name: max_search_results
      label: "Max results:"
      defaultValue: 10
      options:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
  - type: checkbox
    attributes:
      name: download_thumbs
      label: "Download Thumbnails:"
      defaultValue: "true"
      description: Downloading thumbnails can slow down results
  - type: dropdown
    attributes:
      name: language
      label: "Language:"
      defaultValue: Default
      options:
        - Default
        - Afrikaans
        - Azərbaycan
        - Bahasa Indonesia
        - Bahasa Malaysia
        - Bosanski
        - Català
        - Čeština
        - Dansk
        - Deutsch
        - Eesti
        - English (India)
        - English (UK)
        - English (US)
        - Español (España)
        - Español (Latinoamérica)
        - Español (US)
        - Euskara
        - Filipino
        - Français
        - Français (Canada)
        - Galego
        - Hrvatski
        - IsiZulu
        - Íslenska
        - Italiano
        - Kiswahili
        - Latviešu valoda
        - Lietuvių
        - Magyar
        - Nederlands
        - Norsk
        - O‘zbek
        - Polski
        - Português
        - Português (Brasil)
        - Română
        - Shqip
        - Slovenčina
        - Slovenščina
        - Srpski
        - Suomi
        - Svenska
        - Tiếng Việt
        - Türkçe
        - Беларуская
        - Български
        - Кыргызча
        - Қазақ Тілі
        - Македонски
        - Монгол
        - Русский
        - Српски
        - Українська
        - Ελληνικά
        - Հայերեն
        - עברית
        - اردو
        - العربية
        - فارسی
        - नेपाली
        - मराठी
        - हिन्दी
        - অসমীয়া
        - বাংলা
        - ਪੰਜਾਬੀ
        - ગુજરાતી
        - ଓଡ଼ିଆ
        - தமிழ்
        - తెలుగు
        - ಕನ್ನಡ
        - മലയാളം
        - සිංහල
        - ภาษาไทย
        - ລາວ
        - ဗမာ
        - ქართული
        - አማርኛ
        - ខ្មែរ
        - 中文 (简体)
        - 中文 (繁體)
        - 中文 (香港)
        - 日本語
        - 한국어
  - type: dropdown
    attributes:
      name: region
      label: "Region:"
      defaultValue: Default
      options:
        - Default
        - Algeria
        - Argentina
        - Australia
        - Austria
        - Azerbaijan
        - Bahrain
        - Bangladesh
        - Belarus
        - Belgium
        - Bolivia
        - Bosnia and Herzegovina
        - Brazil
        - Bulgaria
        - Canada
        - Chile
        - Colombia
        - Costa Rica
        - Croatia
        - Cyprus
        - Czechia
        - Denmark
        - Dominican Republic
        - Ecuador
        - Egypt
        - El Salvador
        - Estonia
        - Finland
        - France
        - Georgia
        - Germany
        - Ghana
        - Greece
        - Guatemala
        - Honduras
        - Hong Kong
        - Hungary
        - Iceland
        - India
        - Indonesia
        - Iraq
        - Ireland
        - Israel
        - Italy
        - Jamaica
        - Japan
        - Jordan
        - Kazakhstan
        - Kenya
        - Kuwait
        - Latvia
        - Lebanon
        - Libya
        - Liechtenstein
        - Lithuania
        - Luxembourg
        - Malaysia
        - Malta
        - Mexico
        - Montenegro
        - Morocco
        - Nepal
        - Netherlands
        - New Zealand
        - Nicaragua
        - Nigeria
        - North Macedonia
        - Norway
        - Oman
        - Pakistan
        - Panama
        - Papua New Guinea
        - Paraguay
        - Peru
        - Philippines
        - Poland
        - Portugal
        - Puerto Rico
        - Qatar
        - Romania
        - Russia
        - Saudi Arabia
        - Senegal
        - Serbia
        - Singapore
        - Slovakia
        - Slovenia
        - South Africa
        - South Korea
        - Spain
        - Sri Lanka
        - Sweden
        - Switzerland
        - Taiwan
        - Tanzania
        - Thailand
        - Tunisia
        - Turkey
        - Uganda
        - Ukraine
        - United Arab Emirates
        - United Kingdom
        - United States
        - Uruguay
        - Venezuela
        - Vietnam
        - Yemen
        - Zimbabwe
  - type: input
    attributes:
      name: program_path
      label: "Program Path:"
  - type: input
    attributes:
      name: program_args
      label: "Program Arguments:"
```

</details>
